#
# An Alpine image tailored for tmt test suite
#
# tmt/tests/alpine/upstream:latest
#

FROM docker.io/library/alpine:3.22

RUN <<EOF
set -ex

# Populate apk cache
apk update

# Make sure the image is built with the latest packages
apk upgrade
EOF
